### ISSUE TITLE
Support paths relative to solution/project

### ISSUE THREAD

**Issue by fraschfn** [madskristensen/ImagePreview#13]
To document how some algorithms should work in code, I want to use this extension and keep the images in a single folder in the solution or the project.
Right now I use a relative path to the images. Depending on the nesting in folders I have to use varying numbers of "../"s. 
This is not only tedious but also not nice to look at.

It would be great if I could use
   // this diagram shows a sample case: solution:/images/myImage.png
or
   // this diagram shows a sample case: project:/images/myImage.png
instead of 
   // this diagram shows a sample case:   ../../../images/myImage.png

**Comment by madskristensen** [comment]
It supports paths relative to the project, but not the solution. With the latest version of the extension, can you get project relative paths working?

**Comment by fraschfn** [comment]
It works for the project.
I assumed "/" was the root folder.

So instead of this 
```c#
// this diagram shows a sample case: project:/images/myImage.png
```

I have to use this

```c#
// this diagram shows a sample case: /images/myImage.png
```

and it works as I need it.

Relative to the solution was maybe not even a good idea in the first place, so this issue can be closed.

Thanks for your fast response.
