### ISSUE TITLE
[Feature Request] Support for Custom Debugger Working Directories

### ISSUE THREAD

**Issue by Reputeless** [madskristensen/ImagePreview#8]
### Issue Description
In my Visual C++ project, I've customized the debugger's default working directory to `$(ProjectDir)app` instead of the default `$(ProjectDir)`. Because my code references image paths aligned with this custom working directory, the Image Preview extension is unable to resolve them.

### Steps to Reproduce
The debugger's default working directory can be altered by navigating to the following settings path:  
`Project > Properties > Configuration Properties > Debugging > Working Directory`

### Example Code and Project Structure
Here is a C++ code snippet demonstrating the issue:

```cpp
#include <iostream>
#include <fstream>

int main()
{
    std::ifstream file{ "test.png", std::ios::binary }; // Image cannot be previewed
    std::cout << std::boolalpha << file.is_open() << '\n'; // Outputs true
}
```
My project directory structure is as follows:
```
project/
├── test.vcxproj
├── main.cpp
└── app/
    └── test.png
```
**Note:** The debugger's working directory has been set to `$(ProjectDir)app` to align with the image file's location.

### Feature Request
I would like to request support for custom debugger working directories so that the Image Preview extension can correctly resolve image file paths in such scenarios.

**Comment by Reputeless** [comment]
Thank you! I've tried the latest version and confirmed that images are now correctly resolved from the `app` folder. I can start using this extension for my project from today.

While my issue has been completely resolved, it would be convenient for users who use directory names other than the ones you've added support for, to be able to customize these settings via the Options dialog box under the Tools menu.

**Comment by madskristensen** [comment]
If it solves your problem, why do you need settings for it? I hope to be able to solve the 95% case without any settings, since most people never change any settings.

**Comment by Reputeless** [comment]
Fair enough, thanks.
